Repository Samsung/CredSweeper, pull requests merged in 2022-09, with the labels that each got.

#212 Banner with version and CRC32 sum of program files
  .github/workflows/benchmark.yml
  .github/workflows/check.yml
  credsweeper/__init__.py
  credsweeper/__main__.py
  docs/source/guide.rst
  fuzz/fuzzing.sh
  tests/test_app.py
Labels: enhancement

#216 Updated scores after benchmark data updated
  cicd/benchmark.txt
Labels: CI

#215 Argument --depth and workaround
  .github/workflows/check.yml
  credsweeper/config/config.py
  credsweeper/file_handler/file_path_extractor.py
  credsweeper/secret/config.json
  credsweeper/secret/log.yaml
  credsweeper/utils/util.py
  docs/source/overall_architecture.rst
  tests/config/test_config.py
  tests/conftest.py
  tests/test_app.py
  tests/utils/test_util.py
Labels: enhancement

#214 Update KeywordPattern to more accuracy and cover "ENC(" case
  cicd/benchmark.txt
  credsweeper/common/constants.py
  tests/__init__.py
  tests/common/test_constants.py
  tests/rules/test_rule.py
  tests/samples/encrypted_credential
Labels: enhancement

#219 Refactored unit test to avoid undefined behaviour
  tests/test_main.py
Labels: bug

#217 Custom log config
  cicd/missed_docstrings.txt
  cicd/mypy_warnings.txt
  credsweeper/__init__.py
  credsweeper/__main__.py
  credsweeper/config/__init__.py
  credsweeper/config/config_manager.py
  credsweeper/logger/logger.py
  credsweeper/secret/log.yaml
  credsweeper/utils/util.py
  docs/source/config.rst
  docs/source/guide.rst
  tests/__init__.py
  tests/config/test_config.py
  tests/conftest.py
  tests/test_app.py
  tests/test_main.py
  tests/test_utils/dummy_line_data.py
Labels: enhancement
